language: go

go:
  - 1.9

before_script:
  - curl https://glide.sh/get | sh

script: make build-ci

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: VHfqaJqJP0UuUwTvIhB3Txpi7Ny3vUElFGzXZzeXSF5RmEM8flARDG6qPTAlwKzMhbfQM4IiK/mUnP6B9cJ3K6WMe9BibCsDgyT+PsdT50JK6EOGUEjtxOMnWFKUv/YcltOYZQT4WGwSq1iV1M9s38G+h9l4kvvC3H3MJ7j+i6+FXZrM9VLTQltePR65ZaXL78wNdFt3sT70zmTS0bim5TIf+h8qz3Se6wx9C9sYI3NadLG7LOMGyuW+8hibcb2aOWYjRq9vW5RbTefEbrcnFJETiE9THJoRqcpk8yQdAP2/naaxIs9iI2Pk34rlN1v2gph2lvWLJefWJqqq0t4FWkMiYXNkU/ApFq3njgNVM7MZluNBTnoc0cUYljP1VQljfK+yYt1GvN6V+XmUIeMgmQBypxZv6pjtsqhUTMILQKhk4m5Mh1HhzyAXIGhPc0HyvDODeMwmIa75+MLv2oeLIGMBTrMW1hr7CVic+PtzodHXZsU3bT+2ZYHg02KqX+Bpv7O9pPcG4Ng7s08xVHT6XksPvy0JUkD+zbqcMDOzQM+BzjmppslED0mUNHaxubZvrMFjUS9vWpE2qixTmCGzDpeLkYMIjKZlm2ekXz/OzWSxBSxoH7URKWoIF1M+kvh/1q2VlU5PTEyNgmFAIdhK9j4USi0hs9e2GvsjhwJhy6E=
  file:
    - "./dist/gitlab-token-injector"
  on:
    repo: flix-tech/gitlab-token-injector
    tags: true
